baseURL = 'https://theme.projektemacher.org/'
theme = ["projektemacher-base"]
title = "Projektemacher Base"
languageCode = "en"
languagecode = "en"
defaultcontentlanguage = "en"
publishDir = "docs"
canonifyurls = true
disablePathToLower = true

[params.author]
  email = 'mail@christianmahnke.de'
  name = 'Christian Mahnke'
  uri = 'http://www.wikidata.org/entity/Q137668638'

[markup.goldmark.renderer]
  unsafe = true

[imaging]
    quality = 95

[mediaTypes]
  [mediaTypes."application/x-qrcode-template"]
    suffixes = ["json"]

[outputFormats]
  [outputFormats.qrcode]
    mediaType = "application/x-qrcode-template"
    isPlainText = true
    isHTML = false
    baseName = "qrcode"
    notAlternative = true

[security]
  [security.http]
    mediaTypes = ['^application/json$', '^application/json;\s?charset=[uU][tT][fF]-8$', '^application/sparql-results\+json;\s?charset=[uU][tT][fF]-8$']
